#!/bin/bash
#
#
arg="$1"
if ! test -z "$arg"; then
    shift
fi

source ~fmeyer/observatoire_moutherot/obslm.bash

servername="relay_server.py"

piddaemon=$(pidof -x -o %PPID "relayd")
pidserver=$(pidof -x -o %PPID "${servername}")

if test -n "$piddaemon"; then
    #
    # relayd is already running
    #
    #
    # First check if initialisation has been done :
    #   if not, do it once for each relay box:
    if ! test -f "$OLM_R8_SEM"; then
        rdaemonlog " initialising 8 port (KMTronic) relay box "
        olm_init_r8_full
        # wait for relay 16 to come uppp properly
        sleep 10
        touch $OLM_R8_SEM
        if test -n "$OLM_R16_SEM"; then
            if ! test -f "$OLM_R16_SEM"; then
                rdaemonlog " initialising 16 port (chinese) relay box "
                olm_init_r16_full
                touch $OLM_R16_SEM
            fi
        fi
    fi
    case "$arg" in
        "status")
            echo daemon pid = $piddaemon
            if test -n "$pidserver"; then
                echo server pid = $pidserver
            else
                echo server is not running
            fi;;


        "restart")
            if pidserver=$(pidof -x -o %PPID "${servername}"); then
                rdaemonlog " killing server $pidserver"
                kill $pidserver
            else
                rdaemonlog " no server ${servername} running..."
            fi;;

        "stop")
            rdaemonlog " TERMing daemon $piddaemon"
            echo kill $piddaemon
            kill $piddaemon
            echo killall $servername
            killall $servername
            ;;
    esac
    exit
else
    case "$arg" in
        status)
            echo daemon is not running
            if test -n "$pidserver"; then
                echo server pid = $pidserver
            else
                echo server is not running
            fi
            exit ;;

        start|restart)
            rdaemonlog " Daemon is not running, starting it.";;

        stop)
            echo " Daemon is not running, killing server"
            if pidserver=$(pidof -x -o %PPID "${servername}"); then
                rdaemonlog " killing server $pidserver"
                kill $pidserver
            else
                echo " No server ${servername} to kill"
            fi
            exit;;
        *)
    esac
    #
    # run the daemonpart
    #
    cd $OLM_ROOT/relay_server/websys
    (
    while [ 1 ]; do
        pid=$(pidof -x $servername)
        if [ $? == "0" ]; then
            # server is running wait 10 s and go on
            sleep 10
        else
            rdaemonlog "(re)starting $servername"
            ./$servername >>$OLM_SERVERLOG 2>&1
            sleep 1
        fi
    done) &
   disown
fi
