#!/bin/bash
#
#
daemonname=$(basename -- $0)
sudo chown 666 /dev/gpiomem

arg="$1"
if ! test -z "$arg"; then
    shift
fi

source $HOME/observatoire_moutherot/obslm.bash

serverdir="/usr/bin"
servername="indiserver"
serverargs="-f $OLM_IFIFO"

if ! test -p "$OLM_IFIFO"; then
    /bin/rm -f $OLM_IFIFO
    /usr/bin/mkfifo $OLM_IFIFO
fi
if ! test -p "$OLM_IFIFO"; then
    idaemonlog "Fatal error, fifo $OLM_IFIFO cannot be set..."
    exit
fi

piddaemon=$(pidof -o %PPID "${daemonname}")
pidserver=$(pidof -o %PPID "${servername}")

if test -n "$piddaemon"; then
    #
    # indid is already running
    #
    #
    # First check if initialisation has been done :
    #   if not, do it once for each relay box:
    if ! test -f "$OLM_R8_SEM"; then
        idaemonlog " initialising 8 port (KMTronic) relay box "
        olm_init_r8_full
        # wait for relay 16 to come up properly
        sleep 10
        touch $OLM_R8_SEM
        if test -n "$OLM_R16_SEM"; then
            if ! test -f "$OLM_R16_SEM"; then
                idaemonlog " initialising 16 port (chinese) relay box "
                olm_init_r16_full
                touch $OLM_R16_SEM
            fi
        fi
    fi
    case "$arg" in
        "status")
            echo daemon pid = $piddaemon
            if test -n "$pidserver"; then
                echo server pid = $pidserver
            else
                echo server is not running
            fi;;


        "restart")
            if pidserver=$(pidof -o %PPID "${servername}"); then
                idaemonlog " killing server $pidserver"
                kill $pidserver
            else
                idaemonlog " no server ${servername} running..."
            fi;;

        "stop")
            idaemonlog " TERMing (kill) daemon $piddaemon $daemonname"
            kill $piddaemon
            idaemonlog " TERMing  kill pid $piddaemon, killall server $servername,"
            kill $pidserver
            killall $servername
            ;;
    esac
    exit
else
    case "$arg" in
        status)
            echo daemon is not running
            if test -n "$pidserver"; then
                echo server pid = $pidserver
            else
                echo server is not running
            fi
            exit ;;

        start|restart)
            idaemonlog " Daemon is not running, starting it.";;

        stop)
            echo " Daemon is not running, killing server"
            if pidserver=$(pidof -o %PPID "${servername}"); then
                idaemonlog " killing server $pidserver"
                kill $pidserver
            else
                echo " No server ${servername} to kill"
            fi
            exit;;
        *)
    esac
    #
    # run the daemonpart
    #
    (
    while [ 1 ]; do
        pid=$(pidof $servername)
        if test "$?" = "0"; then
            # server is running wait 10 s and go on
            olm_in_status_all
            sleep 10
        else
            idaemonlog "(re)starting $servername, listening on $OLM_IFIFO"
            ${serverdir}/${servername} ${serverargs} >>$OLM_ISERVERLOG 2>&1 &
            sleep 1
            idaemonlog "  -> starting indi drivers "
            olm_in_start_all
            olm_in_sync_eq8_time force
        fi
        sleep 10
    done) &
   disown
fi
